---
title: Greenhouse Gases
class_date: '2023-01-20'
class_number: 5
weight: 5
slug: reading_05
pubdate: '2022-12-31'
date: '2023-01-20'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
pdf_url: /files/reading_asgts/reading_05.pdf
---
## Reading:

### Required Reading (everyone):

* Understanding the Forecast, Ch. 4, Read the whole chapter, but concentrate on pp. 29-34.

### Reading Notes:

You should understand why molecules with many atoms are
more powerful greenhouse gases than molecules with fewer atoms. Can a single
atom (e.g., noble gases such as helium) act as greenhouse gases? What about
nitrogen (N~2~) and oxygen (O~2~) molecules, which make up almost 99% of
the atmosphere?

What is the "**atmospheric window**," that spans the range of about
800--1250 cycles/cm (wavelengths of 8--12 $\mu$m)?

### Understanding emissions spectra seen by satellites

**This is important:** The key to this section is understanding diagrams,
such as Fig. 4.3 and 4.5. These diagrams show the brightness of
infrared light emitted at different frequencies. The smooth lines correspond
to the radiation a perfect blackbody would give off at different temperatures.
Hotter bodies give off more energy and cooler bodies give off less.

The jagged line is the actual radiation given off by the atmosphere, as seen by
a satellite in space. Because the atmosphere is cooler higher up, emissions that
follow a cooler blackbody curve for some part of the spectrum mean the infrared 
at those wavenumbers is emitted by greenhouse gases higher in the atmosphere.
Brighter emissions that follow a hotter blackbody curve for some part of
the spectrum means hotter temperatures, and hence emission at those wavenumbers
comes from gases closer to the ground.

As you add more of a gas, it absorbs more infrared light, so the emissions from
the ground or from lower in the atmosphere can't get through---they're absorbed
by higher layers of the atmosphere---and thus, the only emissions that get out 
to space come from higher (and thus colder) layers. This is why you see lower
emissions (colder temperatures) for the wavenumbers at which powerful greenhouse
gases, such as CO~2~ and ozone, absorb.

Here are some review questions to check whether you understand this material
well:

* Water vapor is a powerful greenhouse gas. Why do you suppose we don't
  see extremely cold temperatures for the part of the spectrum 
  (100--600 cycles/cm) where it absorbs, as we do for CO~2~?
* If greenhouse gases make earth warmer, why does adding CO~2~ in
  make the emissions temperatures become smaller in Fig. 4-5?
