---
title: 'The Carbon Cycle: Mineral Weathering'
class_date: '2023-02-13'
class_number: 15
weight: 15
slug: reading_15
pubdate: '2022-12-31'
date: '2023-02-13'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
pdf_url: /files/reading_asgts/reading_15.pdf
---
## Reading:

### Required Reading (everyone):

* Understanding the Forecast, 8, pp. 95--101.

### Reading Notes:

* Understand the Urey reaction that converts silicate minerals to carbonate minerals and vice-versa.
* How does the Urey reaction behave differently at the surface of the earth (cool temperatures, low pressure) versus
  deep in the earth (hot temperatures and high pressure)?
* Understand key vocabulary: 
  * **Chemical weathering**
  * **Metamorphic decarbonation**
  * **Degassing**
* Whatr is **subduction** and why is it important to the carbon cycle?
* What is the **silicate weathering thermostat**?
  * What determines the "_set-point" of the thermostate?
    * What kinds of changes could move the set-point to a "hot-house" earth, like dinosaurs experienced, or a frozen "snowball earth"?
  * How fast or slow is the thermostat? How many years does it take to respond to changing conditions?
  * How does the silicate-weathering thermostat help to explain why Mars is so cold and Venus is so hot?
