---
title: 'Climate and Oceans: Hurricanes, Sea-level, etc.'
class_date: '2023-04-17'
class_number: 39
weight: 39
slug: reading_39
pubdate: '2022-12-31'
date: '2023-04-17'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
pdf_url: /files/reading_asgts/reading_39.pdf
---
## Reading:

### Required Reading (everyone):

* Climate Casino, 9--10, 12.

### Reading Notes:

Mostly, skim chapters 9--10 and focus on reading chapter 12 carefully.

* In the chapter oceans, there are two distinct threats: sea-level rise and ocean acidification. Get a feel for how each affects people's lives and what adaptations might be possible.
* What sectors of the economy are most vulnerable to climate change?
* What parts of the world are most vulnerable?
* Think about Nordhaus's distinction between managed and unmanaged systems: Does management affect vulnerability to climate change?
* How has the world's economy changed in the last 60 years or so? Which sectors have become more important and which have become less important? What does that imply as we look ahead to the impacts of climate change 100 years from now?
* How do economists estimate the damage climate change might cause to the world economy? How certain are they about these estimates? What are the biggest sources of uncertainty?
* The section on "A Risk Premium" is especialy important. Understand what a risk premium is and how this figures into Nordhaus's thoughts about policy.
