---
title: 'Geoengineering: Carbon Dioxide Management'
class_date: '2023-04-07'
class_number: 35
weight: 35
slug: reading_35
pubdate: '2022-12-31'
date: '2023-04-07'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
pdf_url: /files/reading_asgts/reading_35.pdf
---
## Reading:

### Required Reading (everyone):

* The Climate Fix, Ch. 5, pp. 117--132.
* Climate Casino, Ch. 13, pp. 165--168.
* Handout: [F. Dyson, "The Question of Global Warming," _New York Review of Books_, June 2008](/files/reading_handouts/Dyson-GlobalWarming-2008.pdf){target="_blank"}.

### Reading Notes:

For today we will focus on a second class of geoengineering, called "**air capture**," (Pielke calls this "**carbon remediation**") meaning reducing the atmospheric concentration of CO~2~ by filtering it out of the atmosphere and storing it permanently somewhere.

* How do Pielke and Dyson feel about the prospect of air-capture geoengineering? (You know about Pielke; Dyson is a very famous physicist who is often discussed as a top prospect for a future Nobel Prize).
* How does Pielke think air-capture fits Sarewitz's criteria for a technological fix?
* At the end, when Pielke discusses the "**moral hazard**" argument against geoengineering, what does he mean by "moral hazard?" What do you think about the moral hazard argument?
* What are the implications of geoengineering technology for climate policy in general? How does the prospect of geoengineering shape Dyson's, Nordhaus's, and Pielke's support or opposition to more conventional climate policy that focuses on cutting greenhouse gas emissions?
* What do _you_ think about geoengineering and how does the prospect of geoengineering shape your views of climate policy?
