---
title: 'Geoengineering: Solar Radiation Management'
class_date: '2023-04-05'
class_number: 34
weight: 34
slug: reading_34
pubdate: '2022-12-31'
date: '2023-04-05'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
pdf_url: /files/reading_asgts/reading_34.pdf
---
## Reading:

### Required Reading (everyone):

* The Climate Fix, Ch. 5, pp. 117--132.
* Climate Casino, Ch. 13, Read the whole chapter, but focus especially on pp. 152--156.
* Handout: [L. Burns _et al._, _Solar Geoengineering_, Harvard Belfer Center Technology Factsheet (2019)](/files/reading_handouts/burns_2019_geoengineering_factsheet.pdf){target="_blank"}.

### Optional Extra Reading:

* Handout: [D.G. MacMartin, K.L. Ricke, &  D.W. Keith, "Solar geoengineering as part of an overall strategy for meeting the 1.5&deg;C Paris target," Phil. Trans. Roy. Soc A **376**, 2016054 (2018)](/files/reading_handouts/macmartin_2018_geoengineering_strategy.pdf){target="_blank"}.

### Reading Notes:

We will discuss geoengineering as an alternative to rapidly cutting greenhouse gas emissions. For today, we will focus on **solar radiation management**: Techniques for cancelling out the enhanced greenhouse effect by blocking sunlight from reaching the earth.

* Start with the short factsheet about solar-radiation management geoengineering by Burns. This gives a clear and concise overview of what the big picture is.

* As you read Pielke, pay attention to his discussion of the big picture. What does he mean by a **technological fix**, and what does he think about technological fixes for environmental problems?
* What are Daniel Sarewitz's criteria for successful technological fixes?
* In the context of technological fixes, Pielke describes climate change as a "wicked problem." This is a phrase with a specific meaning in public policy analysis. It comes from a 1973 paper,^[H.W.J. Rittel and M.M. Weber, "[Dilemmas in a General Theory of Planning](https://doi.org/10.1007/BF01405730)," Policy Sciences **4**, 155 (1973).] which defines "wicked problems" as possessing ten different properties, all of which make it very difficult, even impossible, to find satisfactory solutions. A few of these properties include: Wicked problems have high stakes, so it is unacceptable to choose a solution that proves ineffective. They are plagued by uncertainty, so no one can tell in advance whether a solution will work well. They invoilve important tradeoffs, so anything that makes a solution attractive to one constituency will make it unattractive to another. They are irreversible, so trial and error is not an effective approach for finding good solutions.

    As you read this chapter, think about how the problem of geoengineering the climate fits the criteria of a wicked problem.
* What does Pielke think about solar radiation management in terms of Sarewitz's criteria?
* Pielke begins this chapter by discussing geoengineering as a "**Plan B**" for climate policy. What does he mean by this?
* Where Pielke talks about "Plan B," Nordhaus describes geoengineering as "**salvage therapy**" for the planet. How does his account of solar radiation management compare to Pielke's? Where do the two agree and where do they disagree?

* Nordhaus, as an economist, focuses a lot on costs, comparing the costs and the benefits of any policy. How does he asses the costs and benefits of geoengineering?

This optional reading was written by a group of leading experts in climate science and policy about how solar radiation management geoengineering could play an important, but temporary, role in keeping global warming below 1.5&deg;C.
