---
title: The Geochemical Carbon Cycle
due_date: '2023-03-01'
assignment_type: Homework
short_assignment_type: HW
assignment_number: 5
weight: 5
slug: homework_05
pubdate: '2022-12-31'
date: '2023-03-01'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
  pdf_document:
    toc: yes
    toc_depth: 3
pdf_url: /files/homework_asgts/homework_05.pdf
---
## Homework

### Homework Exercises:



* _Forecast_, Ch. 8, Ex. 1--2
* _Forecast_, Ch. 10, Ex.~1
* **Do the following exercise (call it 10.4):**
  Using the SLUGULATOR model at <https://climatemodels.jgilligan.org/slugulator/> or
  <http://climatemodels.uchicago.edu/slugulator/>,
  compare the impact of methane and CO~2~ on timescales of 1, 10, 25, 50, 100,
  500, and 1000 years.

  The SLUGULATOR model simulates releasing a large amount of CO~2~ and
  methane and then calculates what happens over time. At time zero, the
  concentration of each gas is the natural level from shortly before the
  industrial revolution: 280 ppm of CO~2~ and 1.6 ppm of methane. At one year,
  a large amount of each gas is released instantly (after this, there are no
  further emissions of either gas).

  a) Run the model using the default model input parameters, setting the left
     graph to "Concentrations" and the right graph to "Surface T Anomaly".
     Set the time scale on the bottom to show 10 years.

     Move your mouse over the graphs to measure the exact values (a "tooltip" will
     pop up next to the cursor telling the time in years and the value of the line
     on the graph: concentration of CO~2~ or methane, or the warming due to that
     gas). Be aware that on the concentration graph, the concentration of CO~2~
     is plotted against the left axis while methane is plotted against the right
     axis.

     What happens to the concentrations of methane and carbon dioxide? Why does
     the concentration of CO~2~ continue to rise after the first year, when
     methane is falling?
  b) What is the warming due to methane at 1 year and at 10 years? What is the
     warming due to CO~2~ at 1 and 10 years? (Use the mouse to examine the
     time-dependent temperature plotted on the graphs, not the "Time-integrated
     temperature" in the table at the top of the page). Calculate the ratio of
     methane-warming to CO~2~-warming at each time.
  c) Change the time scale to show 25, 50, 100, 500, and 1000 years. Make a table
     showing the warming due to each gas and the ratio of methane-warming to
     CO~2~-warming at 1, 10, 25, 50, 100, 500, and 1000 years.
  d) Plot the ratio of methane-warming to CO~2~-warming over time.
  e) Why does the ratio change with time?
  f) Generating electricity by burning natural gas (methane) releases less than
     half as much CO~2~ than generating the same amount of electricity by
     burning coal.

     "Fracking" has dramatically lowered the cost of natural gas, and this has
     made coal-fired electrical generation uneconomical, so about half of the
     coal generation plants in the United States have shut down in the last 10
     years.

     Many people think replacing coal generation with natural gas generation will
     reduce CO~2~ emissions significantly,
     but gas wells that use fracking also leak a lot of methane directly into the
     atmosphere.

     Comment on the significance of this homework exercise to the debate
     over whether fracking is helping or hurting the problem of global warming.

### Notes on Homework:


The GEOCARB model has two time periods: First, it runs for 5 million years 
with the "Spinup" settings in order to bring the carbon cycle and climate into 
a steady state. Then, at time zero, it abruptly changes the parameters to the 
"Simulation" settings and also dumps a "spike" of CO~2~ into the atmosphere 
and runs for another 2 million years with the new parameters to see how the 
climate and carbon cycle adjust to the new parameters and the CO~2~ spike.

Notice that some of the graphs show short-time behavior (the first 100,000 years 
after the transition) and some show the long-time behavior (two million years 
after the transition).

The quantities that are graphed include:

**pCO2**
  ~  is the concentration of CO~2~ in the atmosphere, in parts per million.
**WeatC**
  ~  is the amount of CO~2~ weathered from carbonate rocks and moved to the 
     oceans.
**BurC**
  ~  is the amount of carbonate converted into limestone and buried on the ocean floor.
**WeatS**
  ~  is the amount of \silica\ weathered from silicate rocks and moved to the oceans.
**Degas**
  ~  is the amount of CO~2~ released to the atmosphere by volcanic activity.
**tco2**
  ~  is the total CO~2~ dissolved in the ocean, adding all its forms: 
     $$\text{tco2} = \ce{[CO2] + [H2CO3] + [{HCO3}-] + [CO3^2-]}.$$
**alk**
  ~  is the ocean alkalinity: the total amount of acid (H^+^) necessary to 
     neutralize the carbonate and bicarbonate in the ocean. The detailed 
     definition is complicated, but to a good approximation, 
     $$\text{alk} = \ce{[HCO3^-] + 2 [CO3^2-]}.$$
     This is not crucial for this homework assignment.
**CO3**
  ~  is the concentration of dissolved carbonate ions (CO~3~^-2^) in the ocean, in moles per cubic meter.
**d13Cocn**
  ~  is the change in the fraction of the carbon-13 (^13^C) isotope 
     relative to the more common carbon-12 (^12^C) isotope in the various 
     forms of carbon dissolved in the ocean water.
**d13Catm**
  ~  is the change in the fraction of ^13^C relative to ^12^C in atmospheric CO~2~.
**Tatm**
  ~  is the average air temperature.
**Tocn**
  ~  is the average water temperature of the oceans.

In this homework, you mostly just look at pCO~2~, but in exercise 2 in 
chapter 8, you also have to look at the weathering.

### Details about the assignment:

**Chapter 8, #1:**
  ~ Run the model with "Transition CO~2~ spike" set to zero and change the 
    CO~2~ degassing rate in the "Simulation" box. Examine how changing in the 
    degassing rate affects the atmospheric concentration of CO~2~, the time 
    it takes to equilibrate (how can you tell when the atmospheric CO~2~ has 
    reached equilibrium?), and how weathering changes to produce this new 
    equilibrium.
    
    If you can't see both the red line and the green line, that's because the
    two lines are identical and the red line is hidden behind the green line.
    
**Chapter 8, #2:**
  ~ I recommend approaching the exercise as follows:
  
    * First, run the simulation with the transition spike set to zero, the 
      degassing rate set to 7.5 in both the spin-up and the simulation and the  
      "Geologic setting" set to 0 (meaning the present).
    * Then press "Save model run to background," which lets you compare this 
      run to a different run.
    * Next, run the model with the geologic setting at 500 million years ago. 
      The sun was substantially dimmer then. How did this affect
      the temperature and
      pCO~2~? 
      
      The original run that you saved (present-day conditions) is labeled as 
      "Alt" in the graphs and the current model run is shown without the "Alt" 
      label. 
      
      The simulation is supposed to reflect a steady state, so if you see 
      pCO~2~ changing, take a careful look at how much it changes during the 
      two million years the graphs cover (it should not change very much, if at 
      all). 
      
      How does the average value of pCO~2~ compare to today? Why is there 
      such a difference?

**Chapter 10, #1:**
  ~ Run the model with year = 0, degassing set to 7.5 for both the spin-up and 
    the simulation, and a spike of 1000. If you want, feel free to run it 
    several times with different values for the spike. 
    You're looking for how long it takes pCO~2~ to level out and how long it 
    takes pCO~2~ to return to its original value (before time zero).

