---
title: Greenhouse Gases and Atmospheric Radiation
due_date: '2023-02-01'
assignment_type: Homework
short_assignment_type: HW
assignment_number: 2
weight: 2
slug: homework_02
pubdate: '2022-12-31'
date: '2023-02-01'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
  pdf_document:
    toc: yes
    toc_depth: 3
pdf_url: /files/homework_asgts/homework_02.pdf
---
## Homework

### Homework Exercises:



* _Forecast_, Ch. 4, Ex. 1 & 3

### Notes on Homework:


* Exercise 1: 
  * Start from the default settings of MODTRAN (400 ppm CO~2~ and 
    1.7 ppm CH~4~, with a tropical atmosphere
    
    In MODTRAN, CO~2~, CH~4~, and stratospheric ozone are given by 
    the concentration in parts per million (ppm) or parts per billion (ppb),
    and tropospheric ozone, water vapor, and freon are given by a "scale", 
    where 1 means the current atmospheric concentration, 2 would mean twice the
    current concentration, and 0.5 would mean half the current concentration.  
  * To see where in the spectrum any greenhouse gas absorbs, you can set all
    the other greenhouse gases to zero.
  * "Equivalent CO~2~" means the change in ppm of CO~2~ that would 
    change the outgoing heat ("Upward IR Flux") by the same amount as 
    adding a certain amount of CH~4~?
* Exercise 3:
  * This exercise introduces the concept of the **water vapor feedback** 
    that we will study in Chapter 7. This is an important contribution to 
    global warming.
  * When you set the temperature offset to a
    nonzero value, you will have the choice of setting the "Holding Constant"
    option to either "Water Vapor Pressure" or "Relative Humidity".
    "Water Vapor Pressure" means the amount of water vapor in the air stays 
    constant when it heats up or cools down (no additional water evaporates or
    condenses). "Relative Humidity" means that when it heats up, extra 
    water evaporates into the atmophere and when it cools off, extra water
    condenses and falls as rain or snow.