---
title: Climate Feedback
due_date: '2023-02-22'
assignment_type: Homework
short_assignment_type: HW
assignment_number: 4
weight: 4
slug: homework_04
pubdate: '2022-12-31'
date: '2023-02-22'
output:
  blogdown::html_page:
    md_extensions: +tex_math_single_backslash+compact_definition_lists
  pdf_document:
    toc: yes
    toc_depth: 3
pdf_url: /files/homework_asgts/homework_04.pdf
---
## Homework

### Homework Exercises:



* Exercises 1--3 from the exercises below.

  These exercises are based on the exercises in _Understanding the Forecast_ Ch. 7,
  but the web interfaces for the models have changed a lot since the book was
  written and you can't do the exercises the way they're written in the book.
  I have written these exercises instead to give you a chance to apply the same
  concepts.


  **Exercise #1:**
    ~ Use the MODTRAN model with the "Tropical Atmosphere" and vary the
      clouds.
      Note that this model does not consider incoming shortwave light, and
      therefore it ignores the albedo effect of clouds. It only calculates the
      effect of the clouds on outgoing longwave light for a given surface
      temperature. One way to think about this is that it looks at the effect the
      clouds have at night.

      a) Run the model three times: First with clear skies, then with
         "Altostratus: Cloud Base 2.4 km, Top 3.0 km,"
         and finally with "Stratus: Cloud Base .33 km, Top 1.0 km."
         Describe the change in \(I_{\text{out}}\) for each type of clouds:

         * Is the effect warming or cooling?
         * Which type of cloud has the bigger effect on $I_{\text{out}}$?
         * Why do you see the difference between the two types of clouds?

      b) Starting set the altitude to zero and select "Looking up." When you
         are looking up, the model reports the longwave radiation coming down to
         the surface from the atmosphere and hitting the earth's surface. This
         heat is in addition to whatever heat the earth gets from shortwave solar
         radiation.

         For simplicity, think of this as the conditions at night, when the sun
         is not shining: without sunlight, the temperature of the ground will be
         determined by balancing the outgoing heat with the heat radiated downward
         by the warm atmosphere and clouds.

         * First, note the downward longwave heat flux ($I_{\text{down}}$) with
         clear sky (no clouds or rain).
         * Then turn on altostratus clouds and note the change in
           $I_{\text{down}}$.
         * Next, turn on stratus clouds and note the change in $I_{\text{down}}$.

         Answer the following questions:

         * How does \(I_{\text{down}}\) change when you add clouds?
         * Do the clouds have a heating or cooling effect? Why?
         * Which clouds have a greater heating or cooling effect? Why?

  **Exercise #2:**
    ~ Use the RRTM model.

      a) First set the model to its default parameters. It should report,
         "If the earth has these properties ... then it loses as much energy as
         it gains."
         Move your mouse over the arrows at the top and bottom of the graph.
         The orange arrows are shortwave (mostly visible) light, and the purple
         arrows are longwave (far-infrared) radiation. How much shortwave and
         longwave light is absorbed by the ground (the downward arrows at the
         bottom) and how much of each is emitted to space (the upward arrows at
         the top)?
      b) Next, add 100% high clouds (set "High cloud (fraction)" to 1.0).
         Record the total gain or loss of of heat, and the amount of shortwave
         and longwave radiation absorbed by the surface and emitted to space.
         Clouds affect both longwave and shortwave heat fluxes. Which kind of
         radiation changed more?
      c) Now do the same thing for low clouds: set "High cloud (fraction)" to
         zero and "Low cloud (fraction)" to 1.0. Which kind of radiation changed
         more, compared to the no-cloud condition?
      d) With the low cloud fraction still set to 1.0 (100%), change the drop
         radius from 10--8 $\mu$m. How does this change the heat flux?
      e) Now set the cloud fraction to zero and double the CO~2~. How does this
         change the heat flux? How does the effect of doubling CO~2~ compare to
         the effect of changing the droplet size for the low clouds? You can see
         how important it is to get the cloud droplet size right in climate
         models!

  **Exercise #3:**
    ~ The "climate sensitivity" ($\Delta T_{\text{2x}}$) refers to the change in
      temperature when you double the amount of CO~2~ in the atmosphere. Here,
      we will examine how the water vapor feedback affects climate sensitivity.

      a) Run the RRTM model with the default parameters. Write down the ground
         temperature.

         Next, double CO~2~ and note the change in energy balance.
         At the beginning of the exercise, the earth was in radiative equilibrium.
         Changing CO~2~ disturbed this equilibrium and produced a radiative
         imbalance where $I_{\text{out}} \neq I_{\text{in}}$.
         Adjust the surface temperature to bring the earth back into balance.

         * What is the new temperature?
         * How much did the earth warm or cool? This temperature change for
           doubling CO~2~ is what we call the **climate sensitivity**,
           or $\Delta T_{2\times\COO}$.

      b) Set CO~2~ back to the default value (400 ppm) and set relative humidity
         to zero. This turns off the water vapor feedback.
         Adjust the surface temperature offset until the earth loses as much
         energy as it gains.
         Write down this temperature.

         Now double the CO~2~ and adjust the surface temperature to bring the
         heat back into balance.

         * How much did the temperature change?

      c) Compare the climate sensitivity with zero relative humidity to the
         sensitivity with the default value of 80% relative humidity. The
         difference is the effect of water vapor feedback.

         * What was the amplification factor of the water vapor feedback
           (the ratio of the climate sensitivity $\Delta T_{2\times\COO}$ with
           water vapor feedback to $\Delta T_{2\times\COO}$ without it)?

